### ISSUE TITLE
indent body?

### ISSUE THREAD

**Issue by blaenk** [johnmastro/react-snippets.el#4]
This is great! I'm wondering if there's any particular reason for why the body isn't indented? The [mocha-snippets](https://github.com/cowboyd/mocha-snippets.el/blob/master/snippets/js-mode/mocha/it.snippet) I found do indent the body which is what I tend to expect.

react-snippets:

```
React.createClass({
$0
});
```

mocha-snippets:

```
it("$1", function() {
  $0
});
```

**Comment by johnmastro** [comment]
Good question - I don't recall for sure why I did it that way. Maybe I thought it would be better to use no indentation, since different people prefer different indentation styles (2 spaces, 4 spaces, tabs, etc.).

However, that doesn't seem very compelling now, since you would only need to hit `TAB` to have Emacs re-indent it.

So, then the question is how many spaces to use. My first thought is 4, since that's the default for both `js-mode` and `js2-mode`. What do you think?

**Comment by blaenk** [comment]
I guess I'm biased because I use and really prefer an indentation of 2 spaces for JavaScript. I may be wrong but I've been under the impression that most JavaScript projects use 2 space indentation.

I'm surprised that yasnippet doesn't have a built in way to handle this situation, or maybe it does and I'm not aware of it.

**Comment by blaenk** [comment]
So there is [`yas-indent-line`](https://joaotavora.github.io/yasnippet/snippet-reference.html#yas-indent-line) which I already have set but doesn't seem to be working for the body line. I wonder if it's because that line is "empty" so there's "nothing" to indent. Perhaps if it were indented even by a fixed amount, it would be indented/corrected automatically.

**Comment by blaenk** [comment]
Yeah I can confirm that seems to be the case. If you indent the body line by 2 spaces, it'll no longer be empty, so `yas-indent-line` will correct that line's indentation if need be. I tested this by creating my own createClass snippet with a body indented by 2 spaces, then setting `js2-basic-offset` to 4 (from 2, after testing with 2) and the body is indeed indented by 4 spaces instead of 2 (and it's not indented by 4 + 2 = 6 either).

**Comment by blaenk** [comment]
If you're open to it, I'll create a PR which indents the bodies of all of the snippets you have where appropriate.

**Comment by johnmastro** [comment]
Sounds good, I'll be happy to merge it. And thanks for pointing out `yas-indent-line` - I either wasn't aware of it or had forgotten about it.

**Comment by blaenk** [comment]
See #5. Let me know what you think.

**Comment by johnmastro** [comment]
Belatedly closing this
