### ISSUE TITLE
add to el-get

### ISSUE THREAD

**Issue by mstorus** [johnmastro/react-snippets.el#8]
Would you consider adding react-snippets to [el-get](https://github.com/dimitri/el-get) ?

**Comment by johnmastro** [comment]
Sure! I'm not an `el-get` user myself and don't have time to experiment with it at the moment. Could you tell me if the recipe below works? I copied it from another recipe and it seems clear enough, but I don't want to submit it totally untested.

```emacs-lisp
(:name react-snippets
       :description "YASnippet snippets for React"
       :depends yasnippet
       :type github
       :pkgname "johnmastro/react-snippets.el")
```

**Comment by mstorus** [comment]
yes, I just tried it locally and it works great. Thanks!

**Comment by johnmastro** [comment]
Thanks for testing it out! I've [submitted it to `el-get` as a pull request](https://github.com/dimitri/el-get/pull/2573)

**Comment by johnmastro** [comment]
My pull request to `el-get` was merged, so I’ll close this issue. Thanks
